# Read the Docs configuration file for TDFOL documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/tdfol/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: requirements-docs.txt
    - method: pip
      path: .

formats:
  - pdf
  - epub
