[PATHS]
local_path = "/storage/cloudkit-models"
ipfs_path = "/storage/ipfs/"
collection_path = "/storage/cloudkit-models/collection.json"

[PATHS.COLLECTION]
local = "/storage/cloudkit-models/collection.json"
s3 = "s3://cloudkit-beta/collection.json"
ipfs =  "QmXBUkLywjKGTWNDMgxknk6FJEYu9fZaEepv3djmnEqEqD"
https = "https://huggingface.co/endomorphosis/cloudkit-collection/resolve/main/collection.json"
orbitdb = "/orbitdb/zdpuB31L6gJz49erikZSQT3A1erJbid8oUTBrjLtBwjjXe3R5"

[HF]
account_name = "endomorphosis"
user_key = "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"
org_key = "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"
org_name = "publicus"

[IPFS]

[IPFS.BOOTSTRAP]
bootstrap = [
"/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
"/ip4/104.131.131.82/udp/4001/quic-v1/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
"/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
"/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
"/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
"/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt"
]

[IPFS.CLUSTER]
clusterName = "cloudkit_storage"
clusterLocation = "/ip4/167.99.96.231/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv"
secret = "96d5952479d0a2f9fbf55076e5ee04802f15ae5452b5faafc98e2bd48cf564d3"

[IPFS.PEERSTORE]
peerlist = [
"/ip4/10.11.0.1/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/10.120.0.2/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/10.46.0.5/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/127.0.0.1/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/167.99.96.231/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/172.17.0.1/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/10.11.0.1/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/10.120.0.2/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/10.46.0.5/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/127.0.0.1/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/167.99.96.231/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/172.17.0.1/tcp/9096/p2p/12D3KooWFHz8Ze2LyrkkL7q3AqMU6TASaYcW2nmzpYwQodsq2SCV",
"/ip4/172.29.29.10/tcp/9096/p2p/12D3KooWNJN6azoq29bY4J3GjE8xQHdYZeQ72Ga6cXnnQ11Jx8fP",
"/ip4/192.168.0.20/tcp/57468/p2p/12D3KooWNJN6azoq29bY4J3GjE8xQHdYZeQ72Ga6cXnnQ11Jx8fP",
"/ip4/97.120.209.166/tcp/18100/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea/p2p-circuit/p2p/12D3KooWNJN6azoq29bY4J3GjE8xQHdYZeQ72Ga6cXnnQ11Jx8fP",
"/ip4/97.120.209.166/tcp/28143/p2p/12D3KooWECihD8h6TooNoqJAVFDsP5MgUiVcy7XYRRmkFM3yyYME/p2p-circuit/p2p/12D3KooWNJN6azoq29bY4J3GjE8xQHdYZeQ72Ga6cXnnQ11Jx8fP",
"/ip4/97.120.209.166/tcp/38053/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea/p2p-circuit/p2p/12D3KooWNJN6azoq29bY4J3GjE8xQHdYZeQ72Ga6cXnnQ11Jx8fP",
"/ip4/167.99.96.231/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv/p2p-circuit/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea",
"/ip4/25.18.152.214/tcp/9096/p2p/12D3KooWECihD8h6TooNoqJAVFDsP5MgUiVcy7XYRRmkFM3yyYME/p2p-circuit/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea",
"/ip4/97.120.129.70/tcp/15289/p2p/12D3KooWECihD8h6TooNoqJAVFDsP5MgUiVcy7XYRRmkFM3yyYME/p2p-circuit/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea",
"/ip4/97.120.209.166/tcp/28143/p2p/12D3KooWECihD8h6TooNoqJAVFDsP5MgUiVcy7XYRRmkFM3yyYME/p2p-circuit/p2p/12D3KooWJ6mj5yii47Hedtfajahmcq1jhU1CmycvKoKoRFWyY4Ea",
"/ip4/10.11.0.1/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/10.120.0.2/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/10.46.0.5/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/127.0.0.1/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/167.99.96.231/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/172.17.0.1/tcp/9096/p2p/12D3KooWKw9XCkdfnf8CkAseryCgS3VVoGQ6HUAkY91Qc6Fvn4yv",
"/ip4/10.11.0.1/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu",
"/ip4/10.120.0.2/tcp/9096/p2p/12D3KooWDYKMnVLKnP2SmM8umJEEKdhug93QYybmNUEiSe1Kwjmu"
]

[ORBITDB]
ipAddress = "127.0.0.1"
dbAddress = "/orbitdb/zdpuB31L6gJz49erikZSQT3A1erJbid8oUTBrjLtBwjjXe3R5"

[MYSQL]
host = "swissknife.mwni.io"
user = "swissknife"
password = "W5!LIGO[pRPO0SdH"
database = "swissknife"

[S3]
bucket ="huggingface-models"
secret_key = "H1osbJRy3903PTMqyOAGD6MIohi4wLXGscnvMEduh10"
access_key = "OVEXCZJJQPUGXZOV"
endpoint = "https://object.ord1.coreweave.com"
host_bucket = "%(bucket)s.object.ord1.coreweave.com"

[PINATA]
ipfs_endpoint = "https://api.pinata.cloud/psa"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI4Y2M2Mzk1YS0wNTkzLTQ0OTItYjA5Yy0wOGYzZDlmZmI3ZmMiLCJlbWFpbCI6InN0YXJ3b3JrczVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siaWQiOiJGUkExIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9LHsiaWQiOiJOWUMxIiwiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjF9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6IjYxN2MwMTUzMDc1OGMwOWNiNTBiIiwic2NvcGVkS2V5U2VjcmV0IjoiMTRmY2QzYWI4MDkwYTJjNjYxOTdkYzM5ZDc0YjQ1OTFkMGQyOTZhZTM4ODdiMTg5YjY5MzIxYWM3MDlhYjFmZCIsImlhdCI6MTcxMzU5MzY5M30.Sqcz8Sf8eTgTuF9V7kmd4wiDwPteynpEXOE4w5MTYK4"
size = "1000000000"
quota = "1000000000"
price = "0.10"
xfer = "0.12"
max_pins = "500"
gateway_key = "2YZKy0PPlG7pK64kuFeQM5e4L9NgEmXd3Wv7KC4GbsoHWCCJlbrsfyz0fq7ZcsKh"
gateway = "https://rose-central-slug-529.mypinata.cloud/%(cid)?pinataGatewayToken=%(gateway_key)"
speed = ""

[LIGHTHOUSE]
ipfs_endpoint = "https://api.lighthouse.storage/api/"
key = "07131fb6.4c17a45d4a9c492888324964349bc998"
size = "1000000"
quota = "1000000"
gateway = "https://gateway.lighthouse.storage/ipfs/%(cid)"
price = "$0.96"
xfer = "$0.10"
encryption = "false"
permanent = "false"
speed = ""

[WEB3STORAGE]
ipfs_endpoint = "https://api.web3.storage/pins"
https_endpoint = "https://up.web3.storage/bridge"
auth_key = "z6MkqZAKNRrnmMPGP6fLdCdnXZSNRKgymAM9qW13C5KwYjE6"
gateway = "https://%(cid).ipfs.w3s.link/"
size = 100000000
quota = 100000000
price = "0.05"
xfer = "0.1"
speed = ""

[FILEBASE]
ipfs_endpoint = "https://api.filebase.io/v1/ipfs"
bucket = "hallucinate"
key = "M0NCNTQ5RTRFQkY4NjZGMzJCQTI6VjBrbWZlclIwMGpudW5sNWJCRXBDS241RVVick5tSEF2MzBGSklNRjpoYWxsdWNpbmF0ZQ=="
gateway = "https://ipfs.filebase.io/ipfs/%(cid)"
s3_endpoint = "https://s3.filebase.com"
price = "0.08"
xfer = "0.015"
max_pins = "1000"
size = "5000000"
quota = "5000000"
speed = ""
