# Workflow Auto-Fix System Configuration
# 
# Updated 2025-10-30: Now properly triggers GitHub Copilot Coding Agent
# by assigning issues to Copilot instead of manually creating PRs.
#
# This file contains configuration for the automated workflow fix system.
# Modify these settings to customize the behavior.

# General Settings
enabled: true
auto_create_pr: false  # Copilot creates PRs automatically
auto_comment_on_issue: true

# Confidence Thresholds
# Only create PRs for fixes with confidence above these thresholds
min_confidence_for_pr: 70
min_confidence_for_auto_label: 80

# Workflow Filtering
# Specify which workflows to monitor (empty = all workflows)
monitored_workflows: []
  # - "Docker Build and Test"
  # - "PDF Processing Pipeline CI/CD"

# Exclude specific workflows from auto-fix
excluded_workflows:
  - "Workflow Auto-Fix System"
  - "Copilot Agent Auto-Healing"
  # Add other workflows that should not be auto-fixed
  # - "Deploy to Production"
  # - "Publish to PyPI"

# Fix Type Settings
fix_types:
  add_dependency:
    enabled: true
    confidence_threshold: 85
    auto_apply: true
  
  increase_timeout:
    enabled: true
    confidence_threshold: 90
    auto_apply: true
    default_timeout_minutes: 30
  
  fix_permissions:
    enabled: true
    confidence_threshold: 75
    auto_apply: true
  
  add_retry:
    enabled: true
    confidence_threshold: 70
    auto_apply: false  # Complex, requires review
  
  fix_docker:
    enabled: true
    confidence_threshold: 80
    auto_apply: false  # Complex, requires review
  
  increase_resources:
    enabled: true
    confidence_threshold: 85
    auto_apply: true
  
  add_env_variable:
    enabled: true
    confidence_threshold: 90
    auto_apply: false  # May contain sensitive data
  
  fix_syntax:
    enabled: true
    confidence_threshold: 80
    auto_apply: false  # Code changes need review
  
  fix_test:
    enabled: true
    confidence_threshold: 60
    auto_apply: false  # Test logic needs review

# PR Settings
pr:
  base_branch: "main"
  create_as_draft: false
  auto_request_review: true
  default_reviewers: []
    # - "username"
  labels:
    - "automated-fix"
    - "workflow-fix"
    - "auto-healing"
  
  # Add these labels based on fix type
  type_specific_labels:
    add_dependency: ["dependencies"]
    fix_permissions: ["configuration"]
    fix_docker: ["docker"]
    fix_test: ["bug"]
    fix_syntax: ["bug"]

# Issue Tracking
issue_tracking:
  enabled: true
  create_tracking_issue: true
  comment_on_existing: true
  close_issue_on_merge: false  # Manual verification required
  
  labels:
    - "automated"
    - "workflow-failure"

# Analysis Settings
analysis:
  max_log_size_mb: 10
  context_lines: 5  # Lines of context around errors
  max_errors_to_analyze: 20
  
  # Custom error patterns (regex)
  custom_patterns: {}
    # your_pattern_name:
    #   patterns:
    #     - "your regex here"
    #   error_type: "Display Name"
    #   fix_type: "custom_fix"
    #   confidence: 75

# Artifact Settings
artifacts:
  retention_days: 30
  upload_logs: true
  upload_analysis: true
  upload_proposal: true

# Notification Settings
notifications:
  github_step_summary: true
  pr_comment: true
  issue_comment: true
  
  # Future: Email, Slack, etc.
  # email:
  #   enabled: false
  #   recipients: []
  # slack:
  #   enabled: false
  #   webhook_url: ""

# Rate Limiting
rate_limiting:
  max_prs_per_workflow_per_day: 3
  max_prs_per_day: 10
  
# Debugging
debug:
  verbose_logging: false
  dry_run: false
  save_intermediate_files: true

# GitHub Copilot Agent Integration (Auto-Healing)
# UPDATED: Now properly triggers Copilot Coding Agent by assigning issues
copilot:
  enabled: true
  use_agent_mode: true  # Use Copilot Agent for automatic implementation
  trigger_method: "issue_assignment"  # Creates issue and assigns to 'Copilot' - this is the official GitHub method
  auto_mention: false    # No longer needed - previously mentioned @copilot in comments, now assignment triggers the agent
  create_task_file: false  # Issue body contains all needed information
  
  # Agent settings
  agent_timeout_hours: 24
  require_agent_completion: false  # Don't block if agent doesn't respond
  fallback_to_manual: false  # Copilot handles everything
  
  # Issue assignment triggers the agent automatically
  # The agent will:
  #   1. Analyze the issue and repository
  #   2. Create a branch for the fix
  #   3. Implement the changes
  #   4. Open a draft PR
  #   5. Request review when ready

# Advanced Settings
advanced:
  # Branch naming pattern
  branch_pattern: "autofix/{workflow}/{fix_type}/{timestamp}"
  
  # Commit message template
  commit_message_template: |
    fix: {title}
    
    This is an automated fix generated by the workflow auto-fix system.
    
    Related workflow run: {run_id}
    Failed workflow: {workflow_name}
    Error type: {error_type}
    Fix confidence: {confidence}%
  
  # PR title template
  pr_title_template: "fix: Auto-fix {error_type} in {workflow_name}"
  
  # Maximum changes per PR
  max_files_per_pr: 5
  
  # Retry settings
  max_retries: 3
  retry_delay_seconds: 60
